### PR TITLE
set E2E_KUBECONFIG

### PR DESCRIPTION
**Pull request by TheoBrigitte**
Towards: https://github.com/giantswarm/giantswarm/issues/4606

Set the `E2E_KUBECONFIG` env var once the cluster is created in order for e2e tests which relies on it.

### CODE REVIEW

**Review by rossf7 — APPROVED** [review]
Very cool and I like that we can just pass a kubeconfig to the wiring in the e2e tests.

**Comment by kopiczko** [comment]
I don't like to set this implicitly. I'd like to see that in the CI script. Otherwise I'm 100% sure we forget how E2E_KUBECONFIG is set. Also how will it be set for a cluster with a different name? Instead I'd prefer to have a command like `e2ectl cluster kubeconfig --name=abcd`.

**Comment by rossf7** [comment]
@kopiczko Yes, I think its clearer if the env var is set by another command and there might be other situations where it's needed. 

I can take splitting it to a new command? As I want to get back to e2ectl. 

WDYT?

cc @TheoBrigitte @MarcelMue

**Comment by kopiczko** [comment]
> I can take splitting it to a new command?

@rossf7 what would be the command here?

Also why not flag instead of env var?

**Comment by rossf7** [comment]
@kopiczko Well I meant the command you suggested `e2ectl cluster kubeconfig --name=abcd` or did I miss something? :)

I'm also interested in the kubeconfig support in `kind` which is still very basic. I think it's on their roadmap to improve.

What I'd like is functionality like `gsctl create kubeconfig` to add it to my local kubeconfig. So then I can use kubectx locally and my prompt is accurate.

**Comment by kopiczko** [comment]
Okay, I got confused because we already have `e2ectl cluster kubeconfig` command. We'd just need to extend it with a flag which makes sense to me.

**Comment by kopiczko** [comment]
Scratch everything I wrote above :D 

Yes what you wrote makes sense :)

**Comment by rossf7** [comment]
Cool thx! I've put a note in my board and I'll do this when I can find some time.

**Comment by sslavic** [comment]
@rossf7 @TheoBrigitte I'm wondering has this exporting of env var side-effect ever worked as "expected"?

As part of working on https://github.com/giantswarm/giantswarm/issues/4606 and following most recent comment https://github.com/giantswarm/giantswarm/pull/6209#discussion_r293421784
I've implemented `e2ectl kubeconfig get` in the https://github.com/giantswarm/e2ectl/tree/kubeconfig-get branch, which basically extracts that `e2ectl cluster create` side-effect behavior to a standalone command + it additionally streams kubeconfig content to stdout. When testing the command, I was (wrongly) expecting env var which was set by the command to be available in my shell after command completes.

This isn't happening because `is.Setenv` sets env var for the current process and all it's child processes only. So, say a CI script runs this new command or old `cluster create` with side-effect, followed by running a new process to execute another command which is supposed to make use of exported environment variable, the variable will not be available to that second follow-up process/command.

That's why `kind create cluster` itself, even in our `e2ectl cluster create` wrapped form, once cluster is successfully created, suggests / outputs instruction:
```
Cluster creation complete. You can now use the cluster with:

export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"
```

@rossf7 should we instead of `e2ectl kubeconfig get` implement kind-equivalent `e2ectl kubeconfig getpath`?

**Comment by rossf7** [comment]
@sslavic Good catch. Another reason it's better to set the env var separately.

I think the command should output the kubeconfig is stdout rather than the file path. So we can use it like this.

```
export E2E_KUBECONFIG="$(e2ectl kubeconfig get --name="kind")"
``` 
We can then use that in the operators and e2e tests.

e.g. https://github.com/giantswarm/app-operator/blob/af025e8b9f306712fc8a14b059032aff41cdcfc2/service/service.go#L67

WDYT?

**Comment by TheoBrigitte** [comment]
Sounds better to be explicit and no set the env variable within e2ectl.

**Comment by sslavic** [comment]
@TheoBrigitte setting env var from e2ectl doesn't work, that will be dropped for sure. Question now is should e2ectl support returning kubeconfig file path or file content.

I see https://github.com/giantswarm/operatorkit/blob/master/client/k8srestconfig/k8s_rest_config.go#L139 expects flag (env var) to contain kubeconfig file content and not the path (which is strange but that's another topic).

Returning path only can accomplish same outcome (as e2ectl returning content) with something like
`export E2E_KUBECONFIG="$(cat $(e2ectl kubeconfig get-path))"`

@rossf7 @TheoBrigitte if you have strong opinion please voice it, make a call; personally I'm fine with either approach, we can support even both at what seems to me as no great expense, important part is that quality and confidence in changes improves so we can ship faster with less risk of breaking things.

**Comment by TheoBrigitte** [comment]
I would say return file path, from this you can always get file content, while the opposite isn't true.

**Comment by rossf7** [comment]
Yes, I'm also fine with `file-path`. Good point it supports both more easily.

**Pull request merged**
